export default {
  Class1: {
    name: "Mango",
    botanicalName: "Mangifera indica",
    family: "Anacardiaceae",
    order: "Sapindales",
    kingdom: "Plantae",
  },
  Class2: {
    name: "Rathmal",
    botanicalName: "Ixora coccinea",
    family: "Rubiaceae",
    order: "Gentianales",
    kingdom: "Plantae",
  },
  Class3: {
    name: "Gotukola",
    botanicalName: "Conservation status",
    family: "Apiaceae",
    order: "Apiales",
    kingdom: "Plantae",
  },
  Class4: {
    name: "Bodhi Tree",
    botanicalName: "Ficus religiosa",
    family: "Moraceae",
    order: "Rosales",
    kingdom: "Plantae",
  },
  Class5: {
    name: "saman pichcha",
    botanicalName: "Jasminum grandiflorum",
    family: "Oleaceae",
    order: "Lamiales",
    kingdom: "Plantae",
  },
  Class6: {
    name: "Nuga Tree",
    botanicalName: "Ficus microcarpa",
    family: "Moraceae",
    order: "Rosales",
    kingdom: "Plantae",
  },
  Class7: {
    name: "patapata kanda kole",
    botanicalName: "Some Botanical Name",
    family: "Some Family",
    order: "",
    kingdom: "Plantae",
  },
  Class8: {
    name: "Bamboo wage kole",
    botanicalName: "Some Botanical Name",
    family: "Some Family",
    order: "",
    kingdom: "Plantae",
  },
};
